### ISSUE TITLE
Travis failures due phpunit strictness

### ISSUE THREAD

**Issue by glensc** [console-helpers/jira-api-restclient#187]
What's up with the phpunit setup on travis?
What is the purpose of such setup?

```yaml
install:
  - if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then composer require "phpunit/phpunit:^4.8" --dev; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.5" ]; then composer install --prefer-dist; fi;

script:
  - if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then ./vendor/bin/phpunit; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.5" ]; then phpunit; fi;
```

Currently travis is failing on 7.2, because it's using travis preinstalled version, that requires `:void` type hints for unit tests.

Example:
```
PHP Fatal error:  Declaration of Tests\chobie\Jira\Api\Client\AbstractClientTestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/chobie/jira-api-restclient/tests/Jira/Api/Client/AbstractClientTestCase.php on line 312
```

I've recently tackled with travis and phpunit, and ended up using `composer global require` only one specific version, so the phpunit deprecations and new methods don't end up conflicting.

https://github.com/eventum/eventum/pull/468

If you describe goal (phpunit version) i'd try to submit PR with that goal

cc @aik099
